// chatService.ts - Tatak Josephinian - Official SJC Merchandise Store
import {
  GREETING_RESPONSE,
  HOW_ARE_YOU_RESPONSE,
  ABOUT_SJC_RESPONSE,
  ABOUT_CREATOR_RESPONSE,
  ABOUT_TATAK_RESPONSE,
  PRODUCTS_RESPONSE,
  PRICING_RESPONSE,
  AVAILABILITY_RESPONSE,
  STORE_RESPONSE,
  PAYMENT_RESPONSE,
  CONTACT_RESPONSE,
  CUSTOM_ORDERS_RESPONSE,
  ORDER_PROCESS_RESPONSE,
  GCASH_DETAILS_RESPONSE,
  THANKS_RESPONSE,
  DEFAULT_RESPONSE,
  NEW_ARRIVALS_RESPONSE,
  SIZING_RESPONSE,
  DOWNPAYMENT_RESPONSE,
  NEED_HELP_RESPONSE,
  CUSTOMER_SERVICE_RESPONSE,
  ORDER_PROBLEM_RESPONSE,
  PAYMENT_ISSUE_RESPONSE,
  CANT_DECIDE_RESPONSE,
  WHAT_TO_ASK_RESPONSE,
  HAVE_QUESTION_RESPONSE,
} from "./chatListResponse";

// Import both the type and the actual suggestion data
import {
  type SuggestedReply,
  contextBasedSuggestions,
  getContextSuggestions,
} from "./suggestedReplies";

// Direct access shortcuts - UPDATED to match EXACT categories from your file
const greetingReplies = contextBasedSuggestions.greetings;
const generalReplies = contextBasedSuggestions.general;
const productsReplies = contextBasedSuggestions.products_overview;
const availabilityReplies = contextBasedSuggestions.availability;
const paymentReplies = contextBasedSuggestions.payment_methods;
const contactReplies = contextBasedSuggestions.contact_info;
const customOrdersReplies = contextBasedSuggestions.custom_orders;
const orderingReplies = contextBasedSuggestions.ordering_process;
const aboutStoreReplies = contextBasedSuggestions.about_store;
const thanksReplies = contextBasedSuggestions.thanks;

export interface Message {
  id: number;
  text: string;
  isBot: boolean;
  timestamp: Date;
}

interface KeywordGroup {
  keywords: string[];
  priority: number;
  response: string;
  suggestions: SuggestedReply[];
}

export interface ChatResponse {
  message: string;
  suggestions: SuggestedReply[];
}

// Calculates match score between user input and keyword arrays for response selection
function calculateMatchScore(input: string, keywords: string[]): number {
  let score = 0;

  keywords.forEach((keyword) => {
    const regex = new RegExp(`\\b${keyword}\\b`, "i");
    if (regex.test(input)) {
      const wordCount = keyword.split(" ").length;
      score += wordCount * 2;
      if (input.includes(keyword.toLowerCase())) {
        score += 3;
      }
    }
  });

  return score;
}

// Main function that processes user input and returns appropriate chatbot response with suggestions
export function getMerchandiseResponse(userInput: string): ChatResponse {
  const input = userInput
    .toLowerCase()
    .replace(/[^\w\s]/g, "")
    .trim();

  const keywordGroups: KeywordGroup[] = [
    {
      keywords: [
        // 🔹 English
        "downpayment",
        "deposit",
        "installment",
        "reservation",
        "prepayment",
        "downpay",
        "advance",
        "partial",
        "payment",
        "installments",
        "dp",
        "initial",
        "first",
        "monthly",
        "reserve",
        "reserving",
        "prepay",
        "depositing",

        // 🔹 Tagalog
        "bayad",
        "hulog",
        "pareserve",
        "paunang",
        "unang",
        "hulugan",
        "reservation",
        "installment",
        "deposit",
        "magbayad",
        "magdeposit",
        "magdownpayment",

        // 🔹 Bisaya / Cebuano
        "hulog",
        "bayad",
        "deposito",
        "pareserve",
        "paunang",
        "unang",
        "downpayment",
        "installment",
        "reservation",
        "advance",
        "partial",
      ],
      priority: 10,
      response: DOWNPAYMENT_RESPONSE,
      suggestions: generalReplies,
    },

    {
      keywords: [
        // 🔹 English
        "gcash",
        "g-cash",
        "payment",
        "pay",
        "paying",
        "paid",
        "transfer",
        "send",
        "money",
        "account",
        "details",
        "number",
        "balance",
        "remit",
        "remittance",
        "deposit",
        "wallet",
        "cash",
        "fund",
        "send money",
        "account number",
        "account details",

        // short essential two-word phrases
        "send money",
        "account number",
        "account details",

        // 🔹 Tagalog
        "bayad",
        "magbayad",
        "nagbayad",
        "pambayad",
        "padala",
        "ipadala",
        "isend",
        "send",
        "gcashpo",
        "bayaran",
        "paymentpo",
        "magpadala",
        "accountpo",
        "detalye",
        "numero",
        "cash",
        "deposito",
        "padalasa",

        // 🔹 Bisaya / Cebuano
        "bayad",
        "magbayad",
        "nagbayad",
        "padala",
        "isend",
        "gcash",
        "deposito",
        "kwarta",
        "pabayad",
        "padalasa",
        "transfer",
        "remit",
        "bayaran",
        "detalye",
        "numero",
      ],
      priority: 10,
      response: GCASH_DETAILS_RESPONSE,
      suggestions: paymentReplies,
    },
    {
      keywords: [
        // 🔹 English
        "custom",
        "customized",
        "personalized",
        "design",
        "designs",
        "customize",
        "customizing",
        "order",
        "orders",
        "bulk",
        "batch",
        "group",
        "organization",
        "team",
        "logo",
        "print",
        "printing",
        "layout",
        "artwork",
        "made",
        "create",
        "created",
        "creative",
        "unique",
        "style",
        "pattern",

        // short essential two-word phrases
        "group order",
        "batch order",
        "custom order",
        "custom design",
        "personalized design",

        // 🔹 Tagalog
        "custom",
        "customized",
        "personalized",
        "design",
        "disenyo",
        "order",
        "umorder",
        "magorder",
        "pareserve",
        "padesign",
        "ipaayos",
        "ipaedit",
        "ipagawa",
        "ipaprint",
        "panggrupo",
        "grupo",
        "organization",
        "team",
        "logo",
        "layout",
        "print",
        "printing",

        // 🔹 Bisaya / Cebuano
        "custom",
        "customized",
        "personalized",
        "design",
        "order",
        "padesign",
        "ipaedit",
        "ipaprint",
        "ipahimo",
        "grupo",
        "team",
        "organization",
        "batch",
        "bulk",
        "print",
        "logo",
      ],

      priority: 10,
      response: CUSTOM_ORDERS_RESPONSE,
      suggestions: customOrdersReplies,
    },

    {
      keywords: [
        // 🔹 English
        "order",
        "ordering",
        "purchase",
        "buy",
        "get",
        "process",
        "steps",
        "checkout",
        "shop",
        "shopping",
        "cart",
        "request",
        "confirm",
        "confirmation",
        "place",
        "placing",
        "acquire",

        // short essential two-word phrases
        "how to order",
        "how to buy",
        "place order",
        "make order",
        "order process",
        "buy now",

        // 🔹 Tagalog
        "order",
        "umorder",
        "magorder",
        "bili",
        "bumili",
        "mabili",
        "kuha",
        "kumuha",
        "proseso",
        "hakbang",
        "hakbangan",
        "checkout",
        "cart",
        "orderin",
        "paano umorder",
        "paano bumili",
        "magpurchase",
        "orderpo",
        "bumilipo",
        "magshop",

        // 🔹 Bisaya / Cebuano
        "order",
        "umorder",
        "magorder",
        "palit",
        "mupalit",
        "kuha",
        "mukuha",
        "proseso",
        "hakbang",
        "checkout",
        "cart",
        "orderon",
        "unsaon pagorder",
        "unsaon pagpalit",
      ],

      priority: 9,
      response: ORDER_PROCESS_RESPONSE,
      suggestions: orderingReplies,
    },
    {
      keywords: [
        // 🔹 English
        "price",
        "pricing",
        "prices",
        "cost",
        "costs",
        "amount",
        "fee",
        "fees",
        "rate",
        "rates",
        "charge",
        "charges",
        "payment",
        "value",
        "worth",
        "estimate",
        "quote",
        "quotation",
        "total",
        "budget",

        // short essential two-word phrases
        "how much",
        "price list",
        "cost list",

        // 🔹 Tagalog
        "presyo",
        "magkano",
        "halaga",
        "bayad",
        "gastos",
        "singil",
        "sisingil",
        "tubo",
        "presyopo",
        "magkanopo",
        "presyong",
        "presyonito",
        "kabuuan",
        "estimate",
        "quote",
        "halagapo",
        "rate",

        // 🔹 Bisaya / Cebuano
        "presyo",
        "tagpila",
        "pila",
        "bayad",
        "gasto",
        "gastos",
        "presyosa",
        "presyopo",
        "payment",
        "amount",
        "fee",
        "rate",
        "singil",
        "estimate",
        "kwenta",
      ],

      priority: 9,
      response: PRICING_RESPONSE,
      suggestions: generalReplies,
    },
    {
      keywords: [
        // 🔹 English
        "available",
        "availability",
        "stock",
        "stocks",
        "instock",
        "outofstock",
        "soldout",
        "have",
        "left",
        "ready",
        "restock",
        "coming",
        "arriving",
        "inventory",
        "supply",
        "remaining",
        "availablenow",
        "availabletoday",
        "stillavailable",

        // short essential phrases
        "in stock",
        "out of stock",
        "sold out",
        "have left",
        "still available",
        "is available",
        "not available",

        // 🔹 Tagalog
        "meron",
        "wala",
        "available",
        "stock",
        "stocks",
        "ubos",
        "mayroon",
        "natitira",
        "naiwan",
        "availablepa",
        "restock",
        "parating",
        "darating",
        "availableba",
        "meronpa",
        "availablepo",
        "meronpang",
        "wala na",
        "soldout",
        "ubosna",

        // 🔹 Bisaya / Cebuano
        "naa",
        "wala",
        "available",
        "stock",
        "stocks",
        "ubos",
        "nahurot",
        "nabilin",
        "restock",
        "abot",
        "abotpa",
        "naa pa",
        "wala na",
        "availablepa",
        "soldout",
      ],

      priority: 7,
      response: AVAILABILITY_RESPONSE,
      suggestions: availabilityReplies,
    },
    {
      keywords: [
        "product",
        "products",
        "item",
        "items",
        "merch",
        "merchandise",
        "accessories",
        "cap",
        "caps",
        "hat",
        "hats",
        "shirt",
        "shirts",
        "t-shirt",
        "t-shirts",
        "bag",
        "bags",
        "tote",
        "umbrella",
        "umbrellas",
      ],
      priority: 9,
      response: PRODUCTS_RESPONSE,
      suggestions: generalReplies,
    },
    {
      keywords: [
        // 🔹 English
        "new",
        "latest",
        "recent",
        "featured",
        "fresh",
        "upcoming",
        "soon",
        "arrival",
        "arrivals",
        "released",
        "release",
        "update",
        "updated",
        "launch",
        "launched",
        "restocked",
        "restock",
        "trending",

        // short essential phrases
        "new arrival",
        "new arrivals",
        "coming soon",
        "just arrived",
        "now available",
        "new release",
        "new collection",

        // 🔹 Tagalog
        "bago",
        "bagong",
        "dumating",
        "parating",
        "darating",
        "feature",
        "featured",
        "new",
        "latest",
        "restock",
        "availablena",
        "bagonglabas",
        "kakadatinglang",
        "bagongdating",
        "paratingpa",
        "trending",
        "bagongitem",
        "bagongdesign",

        // 🔹 Bisaya / Cebuano
        "bag-o",
        "bagong",
        "bago",
        "abtik",
        "bagongabot",
        "abot",
        "abotpa",
        "bagonglabas",
        "coming",
        "soon",
        "restock",
        "available",
        "trending",
        "bagonilabay",
      ],

      priority: 8,
      response: NEW_ARRIVALS_RESPONSE,
      suggestions: productsReplies, // Using productsReplies since new_arrivals doesn't exist
    },
    {
      keywords: [
        // 🔹 English
        "size",
        "sizes",
        "sizing",
        "measurement",
        "measurements",
        "fit",
        "fits",
        "fitting",
        "small",
        "medium",
        "large",
        "xl",
        "xxl",
        "extra",
        "extra large",
        "oversized",
        "loose",
        "tight",
        "chart",
        "guide",

        // short essential phrases
        "size chart",
        "size guide",
        "fit guide",
        "how it fits",
        "true to size",

        // 🔹 Tagalog
        "sukat",
        "sukatan",
        "kasya",
        "kasyado",
        "malaki",
        "maliit",
        "medium",
        "large",
        "xl",
        "xxl",
        "fit",
        "chart",
        "guide",
        "oversized",
        "sizechart",
        "sizeguide",
        "sukatpo",
        "anongsukat",
        "kasya ba",

        // 🔹 Bisaya / Cebuano
        "sukat",
        "kasya",
        "dako",
        "gamay",
        "medium",
        "large",
        "xl",
        "xxl",
        "fit",
        "chart",
        "guide",
        "oversized",
        "sakto",
        "sukatguid",
        "sukatchart",
        "kasya ba",
      ],

      priority: 8,
      response: SIZING_RESPONSE,
      suggestions: getContextSuggestions("apparel"), // Use apparel category for sizing
    },
    {
      keywords: [
        // 🔹 English
        "store",
        "branch",
        "location",
        "locations",
        "place",
        "address",
        "pickup",
        "pick",
        "office",
        "shop",
        "area",
        "where",
        "near",
        "nearby",
        "visit",
        "located",
        "locationmap",
        "map",

        // short essential phrases
        "pick up",
        "physical store",
        "store location",
        "where to buy",
        "store address",
        "visit store",

        // 🔹 Tagalog
        "tindahan",
        "lokasyon",
        "saan",
        "address",
        "opisina",
        "branch",
        "store",
        "shop",
        "pickup",
        "kuha",
        "kunin",
        "pwede kunin",
        "saan banda",
        "saan matatagpuan",
        "saan located",
        "saan makukuha",
        "physical store",
        "puntahan",

        // 🔹 Bisaya / Cebuano
        "tindahan",
        "lokasyon",
        "asa",
        "branch",
        "store",
        "opisina",
        "pickup",
        "kuha",
        "kuhaon",
        "asa dapit",
        "asa makit-an",
        "asa kuhaon",
        "asa naay store",
        "asa naay tindahan",
        "physical store",
        "mapa",
      ],

      priority: 7,
      response: STORE_RESPONSE,
      suggestions: contactReplies, // Use contactReplies for store location
    },
    {
      keywords: [
        // 🔹 English
        "contact",
        "contacts",
        "phone",
        "phones",
        "number",
        "numbers",
        "email",
        "emails",
        "address",
        "addresses",
        "reach",
        "message",
        "facebook",
        "fb",
        "page",
        "messenger",
        "chat",
        "inquire",
        "inquiry",
        "contactinfo",
        "contactus",

        // short essential phrases
        "contact us",
        "send message",
        "send inquiry",
        "reach us",
        "email us",
        "call us",

        // 🔹 Tagalog
        "kontak",
        "numero",
        "telepono",
        "email",
        "gmail",
        "address",
        "tirahan",
        "mensaheng",
        "mensahe",
        "facebook",
        "fb",
        "page",
        "messenger",
        "chat",
        "kausapin",
        "magmessage",
        "maginquire",
        "tawagan",

        // 🔹 Bisaya / Cebuano
        "kontak",
        "numero",
        "telepono",
        "email",
        "address",
        "facebook",
        "fb",
        "messenger",
        "chat",
        "message",
        "inquire",
        "pangutana",
        "tawag",
        "text",
      ],
      priority: 7,
      response: CONTACT_RESPONSE,
      suggestions: contactReplies,
    },
    {
      keywords: [
        // 🔹 English
        "sjc",
        "saint",
        "joseph",
        "college",
        "saint joseph college",
        "st joseph",
        "st joseph college",
        "about sjc",
        "sjc history",
        "sjc background",
        "sjc mission",
        "sjc vision",
        "sjc profile",
        "school",
        "university",
        "institution",

        // short essential phrases
        "about saint joseph college",
        "sjc info",
        "sjc details",

        // 🔹 Tagalog
        "paaralan",
        "kolegio",
        "eskwelahan",
        "tungkol sa sjc",
        "kasaysayan ng sjc",
        "misyon ng sjc",
        "bisyon ng sjc",
        "background ng sjc",
        "tungkol sa college",

        // 🔹 Bisaya / Cebuano
        "kolehiyo",
        "eskwelahan",
        "school",
        "about sjc",
        "kasaysayan",
        "misyon",
        "bisyon",
        "background",
        "saint joseph",
      ],
      priority: 6,
      response: ABOUT_SJC_RESPONSE,
      suggestions: aboutStoreReplies,
    },
    {
      keywords: [
        // 🔹 English
        "tatak",
        "josephinian",
        "tatak josephinian",
        "founder",
        "business",
        "brand",
        "about tatak",
        "official",
        "official store",
        "established",
        "founded",
        "department",
        "bsba",
        "entrepreneurship",
        "store background",
        "mission",
        "vision",

        // short essential phrases
        "about tatak josephinian",
        "official brand",
        "tatak info",
        "tatak background",

        // 🔹 Tagalog
        "tatak",
        "opisyal",
        "store",
        "brand",
        "negosyo",
        "tungkol sa tatak",
        "tatak josephinian",
        "itinayo",
        "itinatag",
        "opisyal na tindahan",
        "opisyal na brand",
        "departamento",
        "bsba",
        "entrepreneurship",

        // 🔹 Bisaya / Cebuano
        "tatak",
        "opisyal",
        "brand",
        "store",
        "negosyo",
        "founder",
        "establisado",
        "tinukod",
        "tatak josephinian",
        "department",
        "bsba",
      ],
      priority: 6,
      response: ABOUT_TATAK_RESPONSE,
      suggestions: aboutStoreReplies,
    },
    {
      keywords: [
        // 🔹 English
        "creator",
        "developer",
        "developed",
        "create",
        "created",
        "chatbot",
        "developerbot",
        "dev",
        "made",
        "madeby",
        "build",
        "built",
        "coder",
        "programmer",
        "designer",
        "development",
        "made this",
        "who made you",
        "created you",
        "created this chatbot",
        "who created you",

        // 🔹 Tagalog
        "gumawa",
        "lumikha",
        "developer",
        "nagdevelop",
        "nagcreate",
        "creator",
        "gumawa ng chatbot",
        "sino gumawa",
        "sino lumikha",
        "programmer",
        "coder",
        "developer ng chatbot",

        // 🔹 Bisaya / Cebuano
        "naghimo",
        "nagbuhat",
        "nagcreate",
        "nagdevelop",
        "kinsa naghimo",
        "kinsa nagbuhat",
        "developer",
        "programmer",
        "creator",
      ],
      priority: 6,
      response: ABOUT_CREATOR_RESPONSE,
      suggestions: generalReplies,
    },
    {
      keywords: [
        // 🔹 English
        "payment",
        "payments",
        "method",
        "methods",
        "option",
        "options",
        "pay",
        "pays",
        "howtopay",
        "gcash",
        "online",
        "transfer",
        "transaction",
        "send",
        "sendmoney",
        "bank",
        "banking",
        "wallet",
        "ewallet",
        "mode",
        "paymode",
        "gcash only",
        "online payment",
        "payment method",
        "payment options",
        "how to pay",

        // 🔹 Tagalog
        "bayad",
        "bayaran",
        "magbayad",
        "paraan ng bayad",
        "gcash",
        "wallet",
        "online",
        "bank",
        "padala",
        "transfer",
        "payment",
        "payments",
        "mode ng bayad",

        // 🔹 Bisaya / Cebuano
        "bayad",
        "magbayad",
        "pabayad",
        "gcash",
        "wallet",
        "bank",
        "online",
        "transaction",
        "padala",
        "payment",
        "method",
      ],
      priority: 6,
      response: PAYMENT_RESPONSE,
      suggestions: paymentReplies,
    },
    {
      keywords: [
        // 🔹 English
        "thank",
        "thanks",
        "thankyou",
        "thank you",
        "appreciate",
        "appreciation",
        "grateful",
        "gratitude",
        "ty",
        "thankful",

        // 🔹 Tagalog
        "salamat",
        "maraming salamat",
        "salamat po",
        "thanks po",
        "thankyou po",
        "napakasalamat",
        "appreciate ko",
        "nagpapasalamat",

        // 🔹 Bisaya / Cebuano
        "salamat",
        "daghang salamat",
        "salamat kaayo",
        "thankyou",
        "thank",
        "thanks",
      ],
      priority: 3,
      response: THANKS_RESPONSE,
      suggestions: thanksReplies,
    },
    {
      keywords: [
        // 🔹 English
        "help",
        "assist",
        "assistance",
        "support",
        "emergency",
        "urgent",
        "problem",
        "issue",
        "trouble",
        "stuck",
        "confused",
        "needhelp",
        "helpme",
        "i need help",
        "need help",

        // 🔹 Tagalog
        "tulong",
        "kailangan ng tulong",
        "patulong",
        "pahelp",
        "problema",
        "hirap",
        "di gumagana",
        "nagkaproblema",
        "supporta",
        "urgent",
        "help po",

        // 🔹 Bisaya / Cebuano
        "tabang",
        "patabang",
        "need help",
        "nanginahanglan",
        "problema",
        "tabangi",
        "tabangi ko",
        "trouble",
        "urgent",
      ],
      priority: 8,
      response: NEED_HELP_RESPONSE,
      suggestions: generalReplies,
    },

    {
      keywords: [
        // 🔹 English
        "service",
        "support",
        "helpdesk",
        "servicedesk",
        "customerservice",
        "customersupport",
        "supportteam",
        "care",
        "customer",
        "assist",
        "assistance",
        "helpline",
        "inquiry",
        "concern",
        "team",

        // short essential phrases
        "customer service",
        "customer support",
        "support team",
        "help desk",
        "service desk",
        "customer care",
        "support center",
        "service center",

        // 🔹 Tagalog
        "serbisyo",
        "customer service",
        "customer support",
        "tulong",
        "suporta",
        "kliyente",
        "team",
        "customer care",
        "service team",
        "helpdesk",
        "serbisyo ng customer",
        "service center",
        "support center",
        "asikaso",
        "assistance",

        // 🔹 Bisaya / Cebuano
        "serbisyo",
        "tabang",
        "suporta",
        "customer",
        "care",
        "customer support",
        "helpdesk",
        "service desk",
        "team",
        "tabang team",
        "serbisyo team",
      ],

      priority: 8,
      response: CUSTOMER_SERVICE_RESPONSE,
      suggestions: generalReplies,
    },
    {
      keywords: [
        // 🔹 English
        "problem",
        "issue",
        "mistake",
        "error",
        "missing",
        "wrong",
        "didnt",
        "haven't",
        "notreceived",
        "receive",
        "received",
        "delay",
        "late",
        "damaged",
        "broken",
        "orderproblem",
        "orderissue",
        "wrongorder",
        "ordererror",
        "missingorder",
        "wrongitem",
        "didn't receive",
        "haven't received",
        "order not received",
        "problem with order",

        // short essential phrases
        "order problem",
        "order issue",
        "missing order",
        "wrong order",
        "order mistake",
        "order error",
        "order delay",
        "delayed order",
        "broken item",
        "wrong item",

        // 🔹 Tagalog
        "problema",
        "issue",
        "mali",
        "kulang",
        "wala pa",
        "di pa nareceive",
        "hindi pa nareceive",
        "nasira",
        "basag",
        "late",
        "delay",
        "wrong order",
        "maling order",
        "kulang sa order",
        "problema sa order",
        "wala pang order",
        "hindi dumating",
        "hindi nareceive",

        // 🔹 Bisaya / Cebuano
        "problema",
        "isyu",
        "mali",
        "sayop",
        "kulang",
        "wala pa",
        "wala nadawat",
        "wala pa nadawat",
        "na delay",
        "ulahi",
        "basag",
        "guba",
        "wrong order",
        "order issue",
        "problema sa order",
      ],

      priority: 9,
      response: ORDER_PROBLEM_RESPONSE,
      suggestions: generalReplies,
    },
    {
      keywords: [
        // 🔹 English
        "payment",
        "issue",
        "problem",
        "error",
        "failed",
        "fail",
        "declined",
        "notworking",
        "trouble",
        "cantpay",
        "unabletopay",
        "transaction",
        "gcash",
        "problem",
        "delay",
        "notprocessed",
        "retry",
        "timeout",
        "payment issue",
        "payment problem",
        "payment error",
        "payment failed",
        "payment not working",
        "payment trouble",
        "transaction issue",
        "gcash problem",
        "gcash error",

        // 🔹 Tagalog
        "problema sa bayad",
        "error sa payment",
        "payment hindi gumagana",
        "hindi makabayad",
        "ayaw gumana",
        "transaction failed",
        "hindi pumapasok",
        "nagfail",
        "payment problem",
        "gcash error",
        "gcash failed",
        "gcash ayaw",

        // 🔹 Bisaya / Cebuano
        "problema sa bayad",
        "bayad error",
        "payment issue",
        "payment problem",
        "dili mabayad",
        "di kabayad",
        "wala ni process",
        "transaction fail",
        "error sa gcash",
        "problema sa gcash",
      ],
      priority: 9,
      response: PAYMENT_ISSUE_RESPONSE,
      suggestions: generalReplies,
    },
    {
      keywords: [
        // 🔹 English
        "confused",
        "unsure",
        "cantdecide",
        "can't decide",
        "dontknow",
        "don't know",
        "whattoask",
        "what to ask",
        "not sure",
        "not sure what to ask",
        "what should i ask",
        "what can i ask",
        "confused what to ask",
        "suggest questions",
        "help me ask",
        "help me decide",

        // 🔹 Tagalog
        "di alam",
        "hindi alam",
        "nalilito",
        "di makapagdecide",
        "hindi makapagdecide",
        "ano itatanong",
        "anong tatanungin",
        "ano pwede itanong",
        "tulungan magtanong",
        "suggestion ng tanong",

        // 🔹 Bisaya / Cebuano
        "wala kabalo",
        "libog",
        "naglibog",
        "di kabalo unsay pangutanon",
        "unsa akong pangutana",
        "unsa pangutana",
        "tabangi ko mag decide",
        "tabang ask",
      ],
      priority: 5,
      response: CANT_DECIDE_RESPONSE,
      suggestions: generalReplies,
    },
    {
      keywords: [
        // 🔹 English
        "what",
        "question",
        "questions",
        "suggest",
        "recommend",
        "ask",
        "topic",
        "suggested",
        "popular",
        "common",
        "frequently",
        "faq",
        "what should i ask",
        "what to ask",
        "suggest questions",
        "recommend questions",
        "good questions",
        "popular questions",
        "common questions",
        "frequently asked",

        // 🔹 Tagalog
        "ano itatanong",
        "anong tatanungin",
        "suggest tanong",
        "rekomendang tanong",
        "madalas itanong",
        "karaniwang tanong",
        "tanong",
        "faq",
        "madalas itanong na tanong",

        // 🔹 Bisaya / Cebuano
        "unsa pangutana",
        "unsa akong pangutana",
        "unsay pangutana",
        "sugyot nga pangutana",
        "kasagaran nga pangutana",
        "common questions",
        "faq",
      ],
      priority: 5,
      response: WHAT_TO_ASK_RESPONSE,
      suggestions: generalReplies,
    },
    {
      keywords: [
        // 🔹 English
        "question",
        "questions",
        "ask",
        "inquiry",
        "query",
        "want",
        "need",
        "askquestion",
        "gotquestion",
        "i have a question",
        "i have questions",
        "got a question",
        "want to ask",
        "need to ask",
        "have inquiry",
        "have query",
        "want to know",
        "curious",

        // 🔹 Tagalog
        "tanong",
        "magtanong",
        "may tanong",
        "gusto magtanong",
        "need magtanong",
        "nais magtanong",
        "may katanungan",
        "gusto ko itanong",
        "inquiry",
        "tanong ko lang",

        // 🔹 Bisaya / Cebuano
        "pangutana",
        "mangutana",
        "gusto mangutana",
        "nangutana",
        "naa koy pangutana",
        "naa koy question",
        "ask ko",
        "gusto ko mangutana",
      ],
      priority: 6,
      response: HAVE_QUESTION_RESPONSE,
      suggestions: generalReplies,
    },
    {
      keywords: [
        // 🔹 English
        "hello",
        "hi",
        "hey",
        "yo",
        "sup",
        "greetings",
        "start",
        "begin",
        "morning",
        "afternoon",
        "evening",
        "goodmorning",
        "goodafternoon",
        "goodevening",
        "start chat",
        "begin chat",

        // 🔹 Tagalog
        "kamusta",
        "mustah",
        "magandang umaga",
        "magandang hapon",
        "magandang gabi",
        "simula",
        "umpisa",
        "hi po",
        "hello po",

        // 🔹 Bisaya / Cebuano
        "kumusta",
        "mustah",
        "ayo",
        "maayong buntag",
        "maayong hapon",
        "maayong gabi",
        "hi",
        "hello",
      ],
      priority: 2,
      response: GREETING_RESPONSE,
      suggestions: greetingReplies,
    },
    {
      keywords: [
        // 🔹 English
        "how",
        "howdy",
        "whatsup",
        "what's up",
        "how are you",
        "how are things",
        "how you doing",
        "how’s everything",
        "sup",

        // 🔹 Tagalog
        "kamusta",
        "musta",
        "kumusta ka",
        "anong balita",
        "mustah",
        "kamusta po",
        "kumusta naman",

        // 🔹 Bisaya / Cebuano
        "kumusta",
        "mustah",
        "unsa na",
        "kumusta ka",
        "kamusta man",
        "unsa imong gibuhat",
      ],
      priority: 1,
      response: HOW_ARE_YOU_RESPONSE,
      suggestions: generalReplies,
    },
  ];

  if (!input) {
    return {
      message: DEFAULT_RESPONSE,
      suggestions: generalReplies,
    };
  }

  let bestMatch: KeywordGroup | null = null;
  let highestScore = 0;

  for (const group of keywordGroups) {
    const score = calculateMatchScore(input, group.keywords);
    if (score > 0) {
      const weightedScore = score * group.priority;
      if (weightedScore > highestScore) {
        highestScore = weightedScore;
        bestMatch = group;
      }
    }
  }

  if (bestMatch && highestScore >= 5) {
    return {
      message: bestMatch.response,
      suggestions: bestMatch.suggestions,
    };
  }

  return {
    message: DEFAULT_RESPONSE,
    suggestions: generalReplies,
  };
}
